### ISSUE TITLE
Add analytics dashboard

### ISSUE THREAD

**Issue by alexgleason** [project-tier/project-tier#4]
I want to implement [tomdyson/wagalytics](https://github.com/tomdyson/wagalytics). Unfortunately there are some issues:

- [x] wagalytics needs to support Wagtail 2.0 (I sent a PR tomdyson/wagalytics#22)
- [x] wagalytics needs to support setting the key from an environment variable (tomdyson/wagalytics#14) so I can deploy to Heroku and keep the key out of the repo
- [x] I need to get the `analytics-key.json` but don't know how (tomdyson/wagalytics#21)
- [x] A new version of wagalytics needs to be deployed with these fixes
- [x] I need to get the `GA_VIEW_ID`
- [x] I need Project TIER to grant me access to their GA account so I can obtain these things once I do know how
- [x] The service account's email address needs to be added to the GA view by Project TIER

**Comment by alexgleason** [comment]
I've created a WIP [`analytics branch`](https://github.com/project-tier/project-tier/compare/analytics), but it relies on a new release of wagalytics before it should be updated and merged.

**Comment by marykatefain** [comment]
They gave me access to this

**Comment by alexgleason** [comment]
Cool, Tom updated the wagalytics package and pushed up version 0.7.

@marykatefain Can you please follow the steps [here](https://github.com/tomdyson/wagalytics/issues/21#issuecomment-363129380) and DM me the private key? We can do this together.

Once we have that we should be ready to deploy this change.

**Comment by alexgleason** [comment]
Okay, it's working! Closing.
